#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker build \
    --build-arg TAG="${DOCKER_TAG}" \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg BUILD_BRANCH="${SOURCE_BRANCH}" \
    --build-arg BUILD_URL="https://github.com/Monogramm/frappe_pwa" \
    --build-arg BUILD_APP=frappe_pwa \
    -f "${DOCKERFILE_PATH}" \
    -t "${IMAGE_NAME}" .
